name: Secret Scan
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  trufflehog:
    name: Scan repo for secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # komplette History für TruffleHog

      - name: Secret scanning with TruffleHog
        uses: trufflesecurity/trufflehog@b2b0a92070f206ab7b5a1105d82a7f2f48d92341 # v3.99.0
        with:
          extra_args: --results=verified,unknown
