name: Secret Scan
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  trufflehog:
    name: Scan repo for secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # komplette History für TruffleHog

      - name: Secret scanning with TruffleHog
        uses: trufflesecurity/trufflehog@20652fbbdefffcdaa493a5bf57ab2ac6b1db715b # v3.97.1
        with:
          extra_args: --results=verified,unknown
